// examples/next/src/app/register/page.tsx
'use client'

import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { toast } from 'sonner'
import { authClient } from '@/lib/auth-client'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { UserPlus } from 'lucide-react'

const schema = z.object({
  name: z.string().min(1),
  cpfCnpj: z.string().min(1),
  email: z.string().email(),
  password: z.string().min(8),
})

type Values = z.infer<typeof schema>

export default function RegisterPage() {
  const router = useRouter()
  const form = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: { name: '', cpfCnpj: '', email: '', password: '' },
  })

  async function onSubmit(values: Values) {
    const { error } = await authClient.signUp.email({
      name: values.name,
      email: values.email,
      password: values.password,
      cpfCnpj: values.cpfCnpj,
    })
    if (error) {
      toast.error('Sign-up failed', { description: error.message })
      return
    }
    router.replace('/payments')
    router.refresh()
  }

  return (
    <div className="flex min-h-[80vh] items-center justify-center p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><UserPlus className="size-5" />Create an account</CardTitle>
          <CardDescription>Sign up to get started.</CardDescription>
        </CardHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)}>
            <CardContent className="space-y-4">
              <FormField control={form.control} name="name" render={({ field }) => (
                <FormItem>
                  <FormLabel>Name</FormLabel>
                  <FormControl><Input placeholder="Jane Doe" {...field} /></FormControl>
                  <FormMessage />
                </FormItem>
              )} />
              <FormField control={form.control} name="cpfCnpj" render={({ field }) => (
                <FormItem>
                  <FormLabel>CPF/CNPJ</FormLabel>
                  <FormControl><Input placeholder="12345678901" {...field} /></FormControl>
                  <FormMessage />
                </FormItem>
              )} />
              <FormField control={form.control} name="email" render={({ field }) => (
                <FormItem>
                  <FormLabel>Email</FormLabel>
                  <FormControl><Input type="email" placeholder="you@example.com" {...field} /></FormControl>
                  <FormMessage />
                </FormItem>
              )} />
              <FormField control={form.control} name="password" render={({ field }) => (
                <FormItem>
                  <FormLabel>Password</FormLabel>
                  <FormControl><Input type="password" placeholder="••••••••" {...field} /></FormControl>
                  <FormMessage />
                </FormItem>
              )} />
            </CardContent>
            <CardFooter className="flex flex-col items-stretch gap-3">
              <Button type="submit" disabled={form.formState.isSubmitting}>
                {form.formState.isSubmitting ? 'Creating…' : 'Sign up'}
              </Button>
              <p className="text-sm text-muted-foreground text-center">
                Already have an account?{' '}
                <Link href="/login" className="text-primary font-medium">Login</Link>
              </p>
            </CardFooter>
          </form>
        </Form>
      </Card>
    </div>
  )
}

// examples/nuxt/app/pages/register.vue
<script setup lang="ts">
import { z } from 'zod'
import type { AuthFormField } from '@nuxt/ui'

const auth = useAuth()
const toast = useToast()

const schema = z.object({
  name: z.string().optional(),
  cpfCnpj: z.string().min(1),
  email: z.email(),
  password: z.string().min(8),
})

const fields: AuthFormField[] = [
  { name: 'name', type: 'text', label: 'Name', placeholder: 'Jane Doe', required: true },
  { name: 'cpfCnpj', type: 'text', label: 'CPF/CNPJ', placeholder: '12345678901', required: true },
  { name: 'email', type: 'email', label: 'Email', placeholder: 'you@example.com', required: true },
  { name: 'password', type: 'password', label: 'Password', placeholder: '••••••••', required: true },
]

async function onSubmit(payload: { data: z.infer<typeof schema> }) {
  const { error, data } = await auth.signUp.email({
    name: payload.data.name || payload.data.email,
    email: payload.data.email,
    password: payload.data.password,
    cpfCnpj: payload.data.cpfCnpj,
  })
  if (error) console.error(error)
  if (error) toast.add({ title: 'Sign-up failed', description: error.message, color: 'error' })
  if (data) await navigateTo('/payments', { replace: true })
}
</script>

<template>
  <div class="flex min-h-screen items-center justify-center p-4">
    <UPageCard class="w-full max-w-md">
      <UAuthForm
        title="Create an account"
        description="Sign up to get started."
        icon="i-lucide-user-plus"
        :fields="fields"
        :schema="schema"
        @submit="onSubmit"
      >
        <template #footer>
          Already have an account?
          <ULink
            to="/login"
            class="text-primary font-medium"
          >Login</ULink>
        </template>
      </UAuthForm>
    </UPageCard>
  </div>
</template>
