// examples/nuxt/app/pages/payments.vue
<script setup lang="ts">
import type { FormSubmitEvent, TableColumn } from '@nuxt/ui'
import { UseClipboard } from '@vueuse/components'
import type { Payment } from 'better-auth-asaas/types'
import { z } from 'zod'

const { $auth } = useNuxtApp()
const toast = useToast()

const schema = z.object({
  value: z.number().positive('Must be > 0'),
  dueDate: z.iso.date(),
  billingType: z.enum(['PIX']).default('PIX'),
  description: z.string().optional(),
})

const state = reactive<z.infer<typeof schema>>({
  value: 100,
  dueDate: '2026-06-20',
  billingType: 'PIX',
  description: 'Test payment',
})

const columns: TableColumn<Payment>[] = [
  { accessorKey: 'id', header: 'ID' },
  { accessorKey: 'value', header: 'Value' },
  { accessorKey: 'dueDate', header: 'Due date' },
  { accessorKey: 'billingType', header: 'Billing type' },
  { accessorKey: 'description', header: 'Description' },
  { id: 'actions', header: 'Actions' },
]

const [
  { data: session, refresh: refreshSession, status: sessionStatus },
  { data: payments, refresh: refreshPayments, status: paymentsStatus, error: paymentsError },
] = await Promise.all([
  $auth.useSession(),
  usePayments(),
])

if (!session.value) await navigateTo('/login', { replace: true })
</script>

<template>
  <div class="grid grid-cols-2 gap-4 w-full">
    <div class="flex flex-col gap-4">
      <!-- form card -->
      <UForm
        :schema="schema"
        :state="state"
        class="flex flex-col gap-4"
        @submit.prevent="async (e: FormSubmitEvent<z.infer<typeof schema>>) => {
          if (!session?.user?.asaasCustomerId) {
            toast.add({ title: 'Error', description: 'User does not have an Asaas customer ID', color: 'error' })
            return
          }

          const { data, error } = await $auth.asaas.payments.create({
            value: e.data.value,
            dueDate: e.data.dueDate,
            billingType: e.data.billingType,
            description: e.data.description,
          })

          if (error) toast.add({ title: 'Error', description: JSON.stringify(error), color: 'error' })
          if (data) toast.add({ title: 'Payment created', description: JSON.stringify(data), color: 'success' })
          if (data) await refreshPayments()
        }"
      >
        <UCard>
          <template #title>
            <div class="flex items-center justify-between">
              Create payment
              <UButton
                type="submit"
                icon="i-lucide-plus"
                variant="ghost"
              />
            </div>
          </template>

          <UFormField
            label="Value"
            name="value"
          >
            <UInput
              v-model="state.value"
              type="number"
              step="1"
            />
          </UFormField>
          <UFormField
            label="Due date"
            name="dueDate"
          >
            <UInput
              v-model="state.dueDate"
              type="date"
            />
          </UFormField>
          <UFormField
            label="Billing type"
            name="billingType"
          >
            <USelect
              v-model="state.billingType"
              default-value="PIX"
              :items="['PIX', 'BOLETO', 'CREDIT_CARD', 'UNDEFINED']"
            />
          </UFormField>
          <UFormField
            label="Description"
            name="description"
          >
            <UInput v-model="state.description" />
          </UFormField>
        </UCard>
      </UForm>

      <!-- session card -->
      <UCard class="overflow-x-auto">
        <template #title>
          <div class="flex items-center justify-between">
            Session
            <UButton
              icon="i-lucide-refresh-cw"
              variant="ghost"
              @click="() => refreshSession()"
            />
          </div>
        </template>

        <pre v-if="sessionStatus === 'success'">{{ session }}</pre>
        <pre v-if="paymentsStatus === 'error'">{{ paymentsError }}</pre>
        <pre v-if="paymentsStatus === 'pending'">Loading...</pre>
      </UCard>
    </div>

    <!-- payments card -->
    <UCard>
      <template #title>
        <div class="flex items-center justify-between">
          Payments
          <UButton
            icon="i-lucide-refresh-cw"
            variant="ghost"
            @click="() => refreshPayments()"
          />
        </div>
      </template>

      <UTable
        :loading="paymentsStatus === 'pending'"
        :columns="columns"
        :data="payments?.data ?? []"
      >
        <template #actions-cell="{ row }">
          <UModal>
            <UButton
              icon="i-lucide-qr-code"
              variant="ghost"
            />
            <template #content>
              <AsyncData
                v-slot="{ data }"
                :fetch-key="['payment', 'qr', row.original.id]"
                :handler="async () => {
                  const { data, error } = await $auth.asaas.payments.qr({ query: { id: row.original.id } })
                  if (error) throw error
                  return data
                }"
              >
                <UCard
                  title="QR"
                  :ui="{ body: 'flex flex-col items-center justify-center gap-4' }"
                >
                  <NuxtImg
                    v-if="data"
                    :src="`data:image/png;base64,${data.encodedImage}`"
                    width="256"
                    height="256"
                  />

                  <UseClipboard v-slot="{ copy }">
                    <UFieldGroup>
                      <UButton
                        label="PIX"
                        icon="i-lucide-copy"
                        class="cursor-pointer"
                        @click="() => {
                          if (!data?.payload) return
                          copy(data.payload)
                          toast.add({ title: 'Copied to clipboard', duration: 1000 })
                        }"
                      />
                      <UInput
                        type="text"
                        disabled
                        :title="data?.payload"
                        :value="data?.payload"
                      />
                    </UFieldGroup>
                  </UseClipboard>
                </UCard>
              </AsyncData>
            </template>
          </UModal>
        </template>
      </UTable>
    </UCard>
  </div>
</template>

// examples/next/src/app/payments/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { Plus, RefreshCw, QrCode, Copy } from 'lucide-react'
import Image from 'next/image'

import { authClient, useSession } from '@/lib/auth-client'
import { usePayments } from '@/hooks/use-payments'
import { useCreatePayment } from '@/hooks/use-create-payment'
import { AsyncData } from '@/components/async-data'

import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

const schema = z.object({
  value: z.coerce.number().positive('Must be > 0'),
  dueDate: z.string().min(1),
  billingType: z.literal('PIX').default('PIX'),
  description: z.string().optional(),
})

type Values = z.infer<typeof schema>

export default function PaymentsPage() {
  const router = useRouter()
  const session = useSession()
  const payments = usePayments()
  const createPayment = useCreatePayment()

  // Lightweight client-side guard, matching the Nuxt example's posture.
  useEffect(() => {
    if (!session.isPending && !session.data?.user) router.replace('/login')
  }, [session.isPending, session.data, router])

  const form = useForm<Values>({
    resolver: zodResolver(schema),
    defaultValues: {
      value: 100,
      dueDate: '2026-06-20',
      billingType: 'PIX',
      description: 'Test payment',
    },
  })

  async function onSubmit(values: Values) {
    await createPayment.mutateAsync(values)
  }

  return (
    <div className="grid w-full gap-4 md:grid-cols-2">
      {/* Left column: form + session */}
      <div className="flex flex-col gap-4">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              Create payment
              <Button type="submit" form="create-payment-form" variant="ghost" size="icon">
                <Plus className="size-4" />
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <Form {...form}>
              <form id="create-payment-form" onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField control={form.control} name="value" render={({ field }) => (
                  <FormItem>
                    <FormLabel>Value</FormLabel>
                    <FormControl><Input type="number" step="1" {...field} /></FormControl>
                    <FormMessage />
                  </FormItem>
                )} />
                <FormField control={form.control} name="dueDate" render={({ field }) => (
                  <FormItem>
                    <FormLabel>Due date</FormLabel>
                    <FormControl><Input type="date" {...field} /></FormControl>
                    <FormMessage />
                  </FormItem>
                )} />
                <FormField control={form.control} name="billingType" render={({ field }) => (
                  <FormItem>
                    <FormLabel>Billing type</FormLabel>
                    <Select onValueChange={field.onChange} value={field.value}>
                      <FormControl>
                        <SelectTrigger><SelectValue /></SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="PIX">PIX</SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                )} />
                <FormField control={form.control} name="description" render={({ field }) => (
                  <FormItem>
                    <FormLabel>Description</FormLabel>
                    <FormControl><Input {...field} /></FormControl>
                    <FormMessage />
                  </FormItem>
                )} />
              </form>
            </Form>
          </CardContent>
        </Card>

        <Card className="overflow-x-auto">
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              Session
              <Button variant="ghost" size="icon" onClick={() => session.refetch()}>
                <RefreshCw className="size-4" />
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <pre className="text-xs">{JSON.stringify(session.data, null, 2)}</pre>
          </CardContent>
        </Card>
      </div>

      {/* Right column: payments table */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            Payments
            <Button variant="ghost" size="icon" onClick={() => payments.refetch()}>
              <RefreshCw className="size-4" />
            </Button>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>ID</TableHead>
                <TableHead>Value</TableHead>
                <TableHead>Due date</TableHead>
                <TableHead>Billing type</TableHead>
                <TableHead>Description</TableHead>
                <TableHead>Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {payments.isPending && (
                <TableRow><TableCell colSpan={6}>Loading…</TableCell></TableRow>
              )}
              {payments.isError && (
                <TableRow><TableCell colSpan={6} className="text-destructive">{String(payments.error)}</TableCell></TableRow>
              )}
              {payments.data?.data?.map((p) => (
                <TableRow key={p.id}>
                  <TableCell>{p.id}</TableCell>
                  <TableCell>{p.value}</TableCell>
                  <TableCell>{p.dueDate}</TableCell>
                  <TableCell>{p.billingType}</TableCell>
                  <TableCell>{p.description}</TableCell>
                  <TableCell><QrButton id={p.id} /></TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}

function QrButton({ id }: { id: string }) {
  const [open, setOpen] = useState(false)
  const qr = useQuery({
    queryKey: ['payment-qr', id],
    enabled: open,
    queryFn: async () => {
      const { data, error } = await authClient.asaas.payments.qr({ query: { id } })
      if (error) throw error
      return data
    },
  })

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="ghost" size="icon"><QrCode className="size-4" /></Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader><DialogTitle>QR</DialogTitle></DialogHeader>
        <AsyncData query={qr}>
          {(data) => (
            <div className="flex flex-col items-center gap-4">
              {data?.encodedImage && (
                <Image
                  src={`data:image/png;base64,${data.encodedImage}`}
                  width={256}
                  height={256}
                  alt="PIX QR code"
                  unoptimized
                />
              )}
              <div className="flex w-full gap-2">
                <Button
                  variant="outline"
                  onClick={() => {
                    if (!data?.payload) return
                    navigator.clipboard.writeText(data.payload)
                    toast.success('Copied to clipboard', { duration: 1000 })
                  }}
                >
                  <Copy className="size-4" />PIX
                </Button>
                <Input readOnly value={data?.payload ?? ''} title={data?.payload ?? ''} />
              </div>
            </div>
          )}
        </AsyncData>
      </DialogContent>
    </Dialog>
  )
}
