// examples/next/src/components/pay-with-credit-card-form.tsx
'use client'

import { useForm } from '@tanstack/react-form'
import { CreditCard } from 'lucide-react'
import { z } from 'zod'

import { payWithCardSchema, payWithCreditCardSchema } from '@meyer1994/better-auth-asaas/zods'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'

type Mode = 'payWithCreditCard' | 'payWithCard'

type PayWithCreditCardValues = z.infer<typeof payWithCreditCardSchema> & {
  mode: 'payWithCreditCard'
}

type PayWithCardValues = z.infer<typeof payWithCardSchema> & {
  mode: 'payWithCard'
}

export type PayWithCardFormValues = PayWithCreditCardValues | PayWithCardValues

type Props = {
  onSubmit: (values: PayWithCardFormValues) => Promise<unknown> | unknown
}

const schema = z.object({
  mode: z.enum(['payWithCreditCard', 'payWithCard']),
  id: z.string().min(1),
  token: z.string().min(1),
}).superRefine((value, context) => {
  const result = value.mode === 'payWithCard'
    ? payWithCardSchema.safeParse({ id: value.id, cardType: 'CREDIT', cardToken: value.token })
    : payWithCreditCardSchema.safeParse({ id: value.id, creditCardToken: value.token })

  if (!result.success) {
    context.addIssue({ code: 'custom', path: ['token'], message: result.error.issues[0]?.message ?? 'Invalid token' })
  }
})
type Item = z.infer<typeof schema>

export function PayWithCreditCardForm({ onSubmit }: Props) {
  const form = useForm({
    defaultValues: {
      mode: 'payWithCreditCard',
      id: '',
      token: '',
    } as Item,

    validators: {
      onSubmit: schema,
    },

    onSubmit: async ({ value }) => {
      if (value.mode === 'payWithCard') {
        await onSubmit({
          mode: 'payWithCard',
          id: value.id,
          cardType: 'CREDIT',
          cardToken: value.token,
        })
        return
      }

      await onSubmit({
        mode: 'payWithCreditCard',
        id: value.id,
        creditCardToken: value.token,
      })
    },
  })

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          Pay with credit card
          <Button type="submit" form="pay-with-cc-form" variant="ghost" size="icon">
            <CreditCard className="size-4" />
          </Button>
        </CardTitle>
      </CardHeader>

      <CardContent>
        <form
          id="pay-with-cc-form"
          onSubmit={(event) => {
            event.preventDefault()
            event.stopPropagation()
            form.handleSubmit()
          }}
          className="space-y-4"
        >
          <form.Field name="mode">
            {(field) => (
              <div className="grid gap-2">
                <Label htmlFor={field.name}>Mode</Label>
                <Select
                  value={field.state.value}
                  onValueChange={(value: string) => field.handleChange(value as Mode)}
                >
                  <SelectTrigger id={field.name}>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="payWithCreditCard">payWithCreditCard</SelectItem>
                    <SelectItem value="payWithCard">payWithCard</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </form.Field>

          <form.Field name="id">
            {(field) => (
              <div className="grid gap-2">
                <Label htmlFor={field.name}>Payment ID</Label>
                <Input
                  id={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="pay_..."
                />
              </div>
            )}
          </form.Field>

          <form.Field name="token">
            {(field) => (
              <div className="grid gap-2">
                <Label htmlFor={field.name}>Card token</Label>
                <Input
                  id={field.name}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={(event) => field.handleChange(event.target.value)}
                  placeholder="tok_..."
                />
              </div>
            )}
          </form.Field>
        </form>
      </CardContent>
    </Card>
  )
}

// examples/nuxt/app/components/payments/PayWithCreditCardForm.vue
<script setup lang="ts">
import type { FormSubmitEvent } from '@nuxt/ui'
import { payWithCreditCardSchema } from '@meyer1994/better-auth-asaas/zods'
import { z } from 'zod'

const emit = defineEmits<{ success: [] }>()

const { $auth } = useNuxtApp()
const toast = useToast()

const schema = payWithCreditCardSchema.safeExtend({
  id: z.string().min(1, 'Required'),
  creditCardToken: z.string().min(1, 'Required'),
})

const state = reactive<z.infer<typeof schema>>({
  id: '',
  creditCardToken: '',
})
</script>

<template>
  <UForm
    :schema="schema"
    :state="state"
    class="flex flex-col gap-4"
    @submit.prevent="async (e: FormSubmitEvent<z.infer<typeof schema>>) => {
      const { data, error } = await $auth.asaas.payments.payWithCreditCard({
        id: e.data.id,
        creditCardToken: e.data.creditCardToken,
      })

      if (error) toast.add({ title: 'Error', description: JSON.stringify(error), color: 'error' })
      if (data) {
        toast.add({ title: 'Paid with credit card', description: JSON.stringify(data), color: 'success' })
        emit('success')
      }
    }"
  >
    <UCard>
      <template #title>
        <div class="flex items-center justify-between">
          Pay with credit card
          <UButton
            type="submit"
            icon="i-lucide-credit-card"
            variant="ghost"
          />
        </div>
      </template>

      <div class="flex flex-col gap-3">
        <UFormField
          label="Payment ID"
          name="id"
        >
          <UInput v-model="state.id" />
        </UFormField>
        <UFormField
          label="Credit card token"
          name="creditCardToken"
        >
          <UInput v-model="state.creditCardToken" />
        </UFormField>
      </div>
    </UCard>
  </UForm>
</template>
